# {json:scada} Demo - (c) 2020-2024 - Ricardo L. Olsen 

# ACCESS VIA WEB BROWSER AT http://127.0.0.1/
# Server must have tcp port 80 free!
# Must be online to connect to IEC60870-5-104 live demo server at 207.180.242.96:2404. 

services:

# NO AUTHENTICATION IS PROVIDED HERE FOR MONGODB AND POSTGRESQL!

  # must create a mongodb instance or cluster with a replica set
  jsdemo_mongorsn1:
    image: mongo:8.0
    container_name: jsdemo_mongors1
    hostname: jsdemo_mongorsn1
    restart: unless-stopped
    command: "mongod --bind_ip_all --replSet rs1 --wiredTigerCacheSizeGB 1 --dbpath /data/db --port 27017"    
    extra_hosts:
      - "jsdemo_mongorsn1:127.0.0.1"
    volumes:
      - ./mongors1/files:/files
      - ./mongo_seed/files:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_DATABASE=json_scada
    # to export mongodb port on main host!
    ports:
      - "27017:27017"
    # internal container port
    expose:
      - "27017"
    networks:
      - jsdemo_net
  
  # Postgresql/TimescaleDB historian. Without auth! 
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: jsdemo_timescaledb
    restart: unless-stopped
    command: postgres -c shared_preload_libraries=timescaledb
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      #- POSTGRES_PASSWORD=passw0rd
    volumes:
      - ./postgres_seed:/docker-entrypoint-initdb.d/
      - ./sql_data:/sql_data
      #- ./timescale:/var/lib/postgresql
    # to export postgresql port on main host!
    ports:
      - 5432:5432
    # internal container port
    expose:
      - "5432"
    links:
      - jsdemo_mongorsn1
    networks:
      - jsdemo_net

  # Postgresql/TimescaleDB Process SQL hist files 
  process_pg_hist:
    image: timescale/timescaledb:latest-pg16
    container_name: jsdemo_process_pg_hist
    command: /sql/process_pg_hist.sh
    restart: unless-stopped
    environment:
      - PSQL_PATH=/usr/local/bin
      - PGPORT=5432
      - PGHOST=jsdemo_timescaledb
      - PGDATABASE=json_scada
      - PGUSER=json_scada
      - PGPASSWORD=
    volumes:
      - ./sql:/sql
    links:
      - jsdemo_mongorsn1
      - timescaledb
    networks:
      - jsdemo_net

  # Postgresql/TimescaleDB Process SQL current data files 
  process_pg_rtdata:
    image: timescale/timescaledb:latest-pg16
    container_name: jsdemo_process_pg_rtdata
    command: /sql/process_pg_rtdata.sh
    restart: unless-stopped
    environment:
      - PSQL_PATH=/usr/local/bin
      - PGPORT=5432
      - PGHOST=jsdemo_timescaledb
      - PGDATABASE=json_scada
      - PGUSER=json_scada
      - PGPASSWORD=
    volumes:
      - ./sql:/sql
    links:
      - jsdemo_mongorsn1
      - timescaledb
    networks:
      - jsdemo_net

  grafana:
    image: grafana/grafana-oss:latest
    container_name: jsdemo_grafana
    # you may need to set the docker user:group to be able to write grafana folder 
    # set UID and GID variables 
    # or change default user and  group ids
    user: "${UID:-1000}:${GID:-1000}"
    restart: unless-stopped
    volumes: 
      - ./grafana_data:/var/lib/grafana
    environment: 
      - GF_SERVER_DOMAIN=grafana
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:8080/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=false
      - GF_AUTH_PROXY_ENABLED=true
      - GF_AUTH_PROXY_ENABLE_LOGIN_TOKEN=true
      - GF_AUTH_DISABLE_SIGNOUT_MENU=true
      # - GF_AUTH_PROXY_WHITELIST=127.0.0.1
      - GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION=true
      - GF_SERVER_HTTP_ADDR=0.0.0.0
      - GF_SERVER_ENFORCE_DOMAIN=true
      - GF_SERVER_ENABLE_GZIP=true
      - GF_ANALYTICS_REPORTING_ENABLED=false
      - GF_ANALYTICS_CHECK_FOR_UPDATES=false
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_DATABASE_TYPE=postgres
      - GF_DATABASE_NAME=grafanaappdb
      - GF_DATABASE_HOST=timescaledb:5432
      - GF_DATABASE_USER=postgres
      #- GF_DATABASE_PASSWORD=
      #- GF_AUTH_PROXY_HEADER_NAME=X-WEBAUTH-USER
      #- GF_AUTH_PROXY_HEADER_PROPERTY=username
      #- GF_AUTH_PROXY_AUTO_SIGN_UP=true      

    # export grafana port to the host
    ports:
      - 3000:3000
    expose:
      - "3000"
    depends_on:
      - timescaledb
    networks:
      - jsdemo_net
  
  # IEC60870-5-104 CLIENT, will connect to a demo server on 207.180.242.96:2404
  iec104client:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    container_name: jsdemo_iec104client
    command: sh -c "sleep 60 && /jsonscada_bin/iec104client"
    restart: unless-stopped
    volumes:
      - ./conf:/conf
      - ./bin:/jsonscada_bin
      - ./log:/log
    links:
      - jsdemo_mongorsn1
    networks:
      - jsdemo_net

  # IEC60870-5-104 SERVER, accepts connection on 127.0.0.1:2404 (originator address 1)
  iec104server:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    container_name:  jsdemo_iec104server
    command: sh -c "sleep 60 && /jsonscada_bin/iec104server"
    restart: unless-stopped
    volumes:
      - ./conf:/conf
      - ./bin:/jsonscada_bin
      - ./log:/log
    links:
      - jsdemo_mongorsn1
    # exports the iec 104 server port to the host
    ports:
      - 2404:2404
    expose:
      - "2404"
    networks:
      - jsdemo_net

  # process incoming data 
  cs_data_processor:
    image: node:20-alpine
    container_name: jsdemo_cs_data_processor
    command:  sh -c "cd /cs_data_processor && sleep 50 && node cs_data_processor.js"
    restart: unless-stopped
    volumes:
      - ../src/cs_data_processor:/cs_data_processor
      - ./sql:/sql
      - ./conf:/conf
      - ./log:/log
    links:
      - jsdemo_mongorsn1
    networks:
      - jsdemo_net

  # custom script processor
  cs_custom_processor:
    image: node:20-alpine
    container_name: jsdemo_cs_custom_processor
    command:  sh -c "cd /cs_custom_processor && sleep 50 && node cs_custom_processor.js"
    restart: unless-stopped
    volumes:
      - ../src/cs_custom_processor:/cs_custom_processor
      - ./conf:/conf
      - ./log:/log
    links:
      - jsdemo_mongorsn1
    networks:
      - jsdemo_net

  # config server for excel
  config_server_excel:
    image: node:20-alpine
    container_name: jsdemo_config_server_excel
    command:  sh -c "cd /config_server_for_excel && sleep 60 && node index.js"
    restart: unless-stopped
    environment:
      - JS_CSEXCEL_IP_BIND=0.0.0.0
      - JS_CSEXCEL_HTTP_PORT=10001
    ports:
      - 10001:10001
    expose:
      - "10001"
    volumes:
      - ../src/config_server_for_excel:/config_server_for_excel
      - ./conf:/conf
      - ./log:/log
    links:
      - jsdemo_mongorsn1
    networks:
      - jsdemo_net

  # mqtt sparkplug-b driver
  mqtt-sparkplug:
    image: node:20-alpine
    container_name: jsdemo_mqtt-sparkplug
    command:  sh -c "cd /mqtt-sparkplug && sleep 60 && node index.js"
    restart: unless-stopped
    volumes:
      - ../src/mqtt-sparkplug:/mqtt-sparkplug
      - ./conf:/conf
      - ./log:/log
    links:
      - jsdemo_mongorsn1
    networks:
      - jsdemo_net

  # OPC-UA Server
  opcua_server:
    image: node:20-alpine
    container_name: jsdemo_opcua_server
    command:  sh -c "cd /OPC-UA-Server && sleep 60 && node index.js"
    restart: unless-stopped
    ports:
      - 4840:4840
    expose:
      - "4840"
    volumes:
      - ../src/OPC-UA-Server:/OPC-UA-Server
      - ./conf:/conf
      - ./log:/log
    links:
      - jsdemo_mongorsn1
    networks:
      - jsdemo_net

  # realtime web server, will listen on some HTTP port with auth, RBAC management UI
  server_realtime:
    image: node:20-alpine
    container_name: jsdemo_server_realtime_auth
    command:  sh -c "cd /server_realtime_auth && sleep 50 && node index.js"
    restart: unless-stopped
    environment:
      - JS_IP_BIND=0.0.0.0
      - JS_HTTP_PORT=8080
      - JS_GRAFANA_SERVER=http://grafana:3000
      - PGPORT=5432
      - PGHOST=jsdemo_timescaledb
      - PGDATABASE=json_scada
      - PGUSER=json_scada
      - PGPASSWORD=
    volumes:
      - ../src/server_realtime_auth:/server_realtime_auth
      #- ../src/htdocs:/htdocs
      #- ../src/htdocs-admin:/htdocs-admin
      #- ../src/htdocs-login:/htdocs-login
      - ../src/AdminUI:/AdminUI
      - ../svg:/svg
      - ./conf:/conf
      - ./log:/log
    links:
      - jsdemo_mongorsn1
      - grafana
    # exports the HTTP port to the main host
    ports:
      - 8080:8080
    expose:
      - "8080"
    networks:
      - jsdemo_net
    
  # calculation process
  calculations:
    image: node:20-alpine
    container_name: jsdemo_calculations
    command:  sh -c "sleep 50 && cd /jsonscada_bin/ && ./calculations"
    restart: unless-stopped
    volumes:
      - ./conf:/conf
      - ./bin:/jsonscada_bin
      - ./log:/log
    links:
      - jsdemo_mongorsn1
    networks:
      - jsdemo_net

  # Dnp3 client: requires wine as it is currently Windows-only
  dnp3_client_wine:
    image: scottyhardy/docker-wine:latest
    container_name: jsdemo_dnp3_client_wine
    #dpkg --add-architecture i386 && apt update && apt install -y xvfb wget libfreetype6 wine wine32:i386 && cd /root &&
    #apt update && apt install -y xvfb wget libfreetype6 wine && cd /root &&
    command: sh -c "export DISPLAY=:0.0 &&
                    export WINEDEBUG=-all &&
                    rm -rf /tmp/.X0-lock && (Xvfb :0 -screen 0 1024x768x16 &) &&
                    cd /tmp &&
                    wget -nc https://download.visualstudio.microsoft.com/download/pr/3c01bbe6-a49d-468f-8335-f195588f582f/b935469e8480e611eae4d79b2e51965e/dotnet-runtime-6.0.33-win-x64.exe ;
                    wget -nc https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks ;
                    sh ./winetricks win10 &&
                    wine dotnet-runtime-6.0.33-win-x64.exe /q &&
                    cd /jsonscada_bin &&
                    sleep 40 &&
                    wine Dnp3Client.exe "
    restart: unless-stopped
    volumes:
      - ./conf:/conf
      - ./bin_win:/jsonscada_bin
      - ./log:/log
    links:
      - jsdemo_mongorsn1
    networks:
      - jsdemo_net

  # OPC-DA client: requires wine as it is currently Windows-only
  opcda_client_wine:
    image: scottyhardy/docker-wine:latest
    container_name: jsdemo_opcda_client_wine
    #dpkg --add-architecture i386 && apt update && apt install -y xvfb wget libfreetype6 wine wine32:i386 && cd /root &&
    #apt update && apt install -y xvfb wget libfreetype6 wine && cd /root &&
    command: sh -c "export DISPLAY=:0.0 &&
                    export WINEDEBUG=-all &&
                    rm -rf /tmp/.X0-lock && (Xvfb :0 -screen 0 1024x768x16 &) &&
                    cd /tmp &&
                    wget -nc https://download.visualstudio.microsoft.com/download/pr/3c01bbe6-a49d-468f-8335-f195588f582f/b935469e8480e611eae4d79b2e51965e/dotnet-runtime-6.0.33-win-x64.exe ;
                    wget -nc https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks ;
                    sh ./winetricks win10 &&
                    wine dotnet-runtime-6.0.33-win-x64.exe /q &&
                    cd /jsonscada_bin &&
                    sleep 40 &&
                    wine OPC-DA-Client.exe "
    restart: unless-stopped
    volumes:
      - ./conf:/conf
      - ./bin_win:/jsonscada_bin
      - ./log:/log
    links:
      - jsdemo_mongorsn1
    networks:
      - jsdemo_net

#  # Metabase for dashboards (can connect to MONGODB and POSTGRESQL)
#  metabase:
#    image: metabase/metabase:latest
#    container_name: jsdemo_metabase
#    restart: unless-stopped
#    ports:
#      - 3001:3000
#    links:
#      - jsdemo_mongorsn1
#      - timescaledb
#    networks:
#      - jsdemo_net

  nginx:
    image: nginx:latest
    container_name: jsdemo_nginx
    ports:
      - "80:80"
    expose:
      - "80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/fastcgi.conf:/etc/nginx/fastcgi.conf
      - ./conf/nginx-conf.d:/etc/nginx/conf.d
      - ../src/AdminUI:/AdminUI
      - ../svg:/svg
    restart: unless-stopped
    links:
      - server_realtime
    networks:
      - jsdemo_net

networks:
  jsdemo_net:
    driver: bridge
